name: api-open-weather

on:
    push:
      branches: [main] 
      
jobs:
api-open-weather:
          runs-on: ubuntu-latest
          
          steps:
          
            - uses: actions/checkout@3.1.0
            
            - name: Docker Login
              uses: docker/login-action@2.1.0
              with:
                username: ${{ secrets.USER}}      
                password: ${{ secrets.PASSWORD}}
                
            - name: Build and push Docker images
              uses: docker/build-push-actions@3.2.0
              with:
                context: .
                file: .
                push: true
                tags: |
                  thainandiego/testeapi
                  thainandiego/testeapi:latest
